<Project Sdk="Dalamud.NET.Sdk/15.0.0">
<PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><Version>0.1.0.1</Version><Authors>Roxyz0501</Authors><PackageLicenseExpression>MIT</PackageLicenseExpression><RepoUrl>https://github.com/Roxyz0501/AllaganLocal</RepoUrl><IconUrl>https://raw.githubusercontent.com/Roxyz0501/AllaganLocal/main/images/icon.png</IconUrl><DalamudLibPath>$(appdata)/XIVLauncher/addon/Hooks/dev/</DalamudLibPath></PropertyGroup>
<ItemGroup><Compile Remove="HostTests/**/*.cs" /></ItemGroup></Project>
