<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AllowUnsafeBlocks>true</AllowUnsafeBlocks><SdkRoot>$(APPDATA)/XIVLauncher/addon/Hooks/dev</SdkRoot></PropertyGroup>
<ItemGroup><Compile Include="../UiFonts.cs" Link="UiFonts.cs"/><Reference Include="Dalamud"><HintPath>$(SdkRoot)/Dalamud.dll</HintPath></Reference><Reference Include="Dalamud.Bindings.ImGui"><HintPath>$(SdkRoot)/Dalamud.Bindings.ImGui.dll</HintPath></Reference><None Include="$(SdkRoot)/cimgui.dll" Link="cimgui.dll" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
